kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ name }}
  annotations: {{ ingress_annotations }}
spec:
{% if routing['tls']['enabled'] %}
  tls:
    - hosts:
        - {{ routing["host"] }}
      secretName: {{ routing["tls"]["secretName"] }}
{% endif %}
  rules:
    - host: {{ routing["host"] }}
      http:
        paths:
        - path: {{ routing["path"] }}
          backend:
            serviceName: {{ name }}
            servicePort: 80
